[package]
name = "pardiso-wrapper"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Wrappers for MKL and Panua Pardiso dynamic libraries"

[lib]
name = "pardiso_wrapper"
crate-type = ["rlib"]

[dependencies]
cfg-if = "1.0.0"
lazy_static = "1.5.0"
libloading = "0.8.6"
num_enum = "0.7.3"
thiserror = "2.0.12"
which = "7.0.3"

[features]
default = ["panua"]
panua = []
mkl = []

[dev-dependencies]
approx = "0.5"
